# -*- coding: utf-8 -*-
"""initial migration

Revision ID: 3502886605d8
Revises:
Create Date: 2022-09-26 10:28:17.925076

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3502886605d8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("screen_name", sa.String(length=100), nullable=True),
        sa.Column("email_address", sa.Text(), nullable=False),
        sa.Column("profile_picture", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.String(length=100), nullable=False),
        sa.Column("registered_on", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_authenticated", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("interests", postgresql.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("follows", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("followers", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("author")
    # ### end Alembic commands ###
